import { Table } from '@interfaces/tables.interface'

const tableModel: Table[] = [
  { id: 1, firstName: 'basin', lastName: 'cattle', age: 16, mood: 37 },
  { id: 2, firstName: 'inflation', lastName: 'youth', age: 1, mood: 56 },
  { id: 3, firstName: 'complaint', lastName: 'trade', age: 7, mood: 10 },
  { id: 4, firstName: 'pancake', lastName: 'dog', age: 10, mood: 73 },
  { id: 5, firstName: 'lock', lastName: 'son', age: 12, mood: 5 },
  { id: 6, firstName: 'dealer', lastName: 'variety', age: 29, mood: 63 },
  { id: 7, firstName: 'worm', lastName: 'design', age: 27, mood: 16 },
  { id: 8, firstName: 'apparatus', lastName: 'quicksand', age: 25, mood: 16 },
  { id: 9, firstName: 'attitude', lastName: 'cent', age: 11, mood: 49 },
  { id: 10, firstName: 'reading', lastName: 'cap', age: 12, mood: 74 },
  { id: 11, firstName: 'wealth', lastName: 'plot', age: 13, mood: 79 },
  { id: 12, firstName: 'dinosaurs', lastName: 'spot', age: 4, mood: 98 },
  { id: 13, firstName: 'management', lastName: 'collar', age: 26, mood: 15 },
  { id: 14, firstName: 'things', lastName: 'aunt', age: 19, mood: 81 },
  { id: 15, firstName: 'thanks', lastName: 'stew', age: 12, mood: 53 },
  { id: 16, firstName: 'steam', lastName: 'freedom', age: 0, mood: 53 },
  { id: 17, firstName: 'restaurant', lastName: 'girlfriend', age: 19, mood: 45 },
  { id: 18, firstName: 'performance', lastName: 'chance', age: 25, mood: 12 },
  { id: 19, firstName: 'parent', lastName: 'month', age: 17, mood: 87 },
  { id: 20, firstName: 'accident', lastName: 'month', age: 13, mood: 97 },
  { id: 21, firstName: 'inflation', lastName: 'youth', age: 1, mood: 56 },
  { id: 22, firstName: 'complaint', lastName: 'trade', age: 7, mood: 10 },
  { id: 23, firstName: 'pancake', lastName: 'dog', age: 10, mood: 73 },
  { id: 24, firstName: 'lock', lastName: 'son', age: 12, mood: 5 },
  { id: 25, firstName: 'dealer', lastName: 'variety', age: 29, mood: 63 },
  { id: 26, firstName: 'worm', lastName: 'design', age: 27, mood: 16 },
  { id: 27, firstName: 'apparatus', lastName: 'quicksand', age: 25, mood: 16 },
  { id: 28, firstName: 'attitude', lastName: 'cent', age: 11, mood: 49 },
  { id: 29, firstName: 'reading', lastName: 'cap', age: 12, mood: 74 },
  { id: 30, firstName: 'wealth', lastName: 'plot', age: 13, mood: 79 },
  { id: 31, firstName: 'dinosaurs', lastName: 'spot', age: 4, mood: 98 },
  { id: 32, firstName: 'management', lastName: 'collar', age: 26, mood: 15 },
  { id: 33, firstName: 'things', lastName: 'aunt', age: 19, mood: 81 },
  { id: 34, firstName: 'thanks', lastName: 'stew', age: 12, mood: 53 },
  { id: 35, firstName: 'steam', lastName: 'freedom', age: 0, mood: 53 },
  { id: 36, firstName: 'restaurant', lastName: 'girlfriend', age: 19, mood: 45 },
  { id: 37, firstName: 'performance', lastName: 'chance', age: 25, mood: 12 },
  { id: 38, firstName: 'parent', lastName: 'month', age: 17, mood: 87 },
]

export default tableModel
